# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=191, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_accounting', models.BooleanField(default=False)),
                ('is_warehouse', models.BooleanField(default=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(db_column='adminid', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='user', max_length=100)),
                ('password', models.CharField(blank=True, db_column='pass', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, db_column='createdbyadminid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.AdminUser')),
                ('is_authority', models.BooleanField(db_column='authority', default=False)),
                ('is_founder', models.BooleanField(db_column='founder', default=False)),
                ('full_name', models.CharField(blank=True, db_column='fullname', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=192)),
                ('about', models.TextField(blank=True)),
                ('access_level', models.IntegerField(choices=[(1, 'Admin'), (2, 'Customer Management'), (3, 'Product Management'), (4, 'Marketing Only'), (5, 'BBS Only')], db_column='acclev')),
                ('is_sleeping', models.BooleanField(db_column='sleeping', default=False)),
                ('date_created', models.DateTimeField(db_column='stamp', auto_now_add=True)),
                ('pic_first_name', models.CharField(blank=True, db_column='picfname', max_length=255)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='cell', max_length=30)),
                ('two_factor_type', models.IntegerField(choices=[(1, 'OTP auth'), (2, 'SMS auth')], db_column='twofac')),
                ('is_active', models.BooleanField(db_column='enable', default=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='customerid', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=192)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('is_preferred', models.BooleanField(db_column='preferred', default=False)),
                ('is_active', models.BooleanField(db_column='enabled', default=True)),
                ('notes', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, db_column='coname', max_length=150)),
                ('has_warehousing', models.BooleanField(db_column='warehousing', default=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('last_login_client', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustContact',
            fields=[
                ('id', models.AutoField(db_column='custcontactid', primary_key=True, serialize=False)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('email', models.EmailField(blank=True, max_length=192)),
                ('password', models.CharField(blank=True, db_column='pass', max_length=255)),
                ('first_name', models.CharField(blank=True, db_column='fname', max_length=150)),
                ('last_name', models.CharField(blank=True, db_column='lname', max_length=150)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='tel', max_length=30)),
                ('phone_extension', models.CharField(blank=True, db_column='telext', max_length=5)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(db_column='fax', blank=True, max_length=30)),
                ('is_primary', models.BooleanField(db_column='isprimary', default=False)),
                ('is_active', models.BooleanField(db_column='enabled', default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='lastlogin', null=True)),
                ('notes', models.TextField(blank=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='mobile', max_length=30)),
            ],
            options={
                'db_table': 'CustContacts',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(db_column='locationid', primary_key=True, serialize=False)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='tel', max_length=30)),
                ('phone_extension', models.CharField(blank=True, db_column='telext', max_length=5)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, db_column='addr', max_length=150)),
                ('address_2', models.CharField(blank=True, db_column='addr2', max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('non_us_state', models.CharField(blank=True, db_column='ostate', max_length=150)),
                ('customer_contact', models.ForeignKey(db_column='custcontactid', on_delete=django.db.models.deletion.CASCADE, to='ims.CustContact')),
                ('notes', models.TextField(blank=True)),
                ('receiving_hours', models.CharField(blank=True, db_column='recvhours', max_length=100)),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(db_column='palletid', primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='PID', max_length=10)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
            ],
            options={
                'db_table': 'Pallets',
            },
        ),
        migrations.CreateModel(
            name='PalletContents',
            fields=[
                ('id', models.AutoField(db_column='onpalletid', primary_key=True, serialize=False)),
                ('cases', models.IntegerField(db_column='qty')),
                ('pallet', models.ForeignKey(db_column='palletid', on_delete=django.db.models.deletion.CASCADE, to='ims.Pallet')),
            ],
            options={
                'db_table': 'OnPallet',
                'verbose_name_plural': 'pallet contents',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='productid', primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='PRID', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('packing', models.IntegerField(blank=True, null=True)),
                ('cases_inventory', models.IntegerField(blank=True, db_column='remain', null=True)),
                ('units_inventory', models.IntegerField(blank=True, db_column='totalq', null=True)),
                ('unit_price', models.FloatField(blank=True, db_column='unitprice', null=True)),
                ('gross_weight', models.FloatField(blank=True, db_column='GW', null=True)),
                ('is_domestic', models.BooleanField(db_column='prodtype', default=False)),
                ('name', models.CharField(blank=True, db_column='pname', max_length=255)),
                ('client_product_id', models.CharField(blank=True, db_column='ctag', max_length=24)),
                ('contracted_quantity', models.BigIntegerField(blank=True, db_column='contqty', null=True)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('length', models.CharField(blank=True, max_length=10)),
                ('width', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('item_number', models.CharField(blank=True, db_column='itemnum', max_length=12)),
                ('account_prepay_type', models.IntegerField(choices=[(1, 'INVQ'), (2, 'Prepaid')], db_column='account')),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('location', models.ForeignKey(blank=True, db_column='locationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Location')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(db_column='receivableid', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('purchase_order', models.CharField(blank=True, db_column='PO', max_length=50)),
                ('shipment_order', models.CharField(blank=True, db_column='SO', max_length=50)),
                ('cases', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('product', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='ims.Product')),
            ],
            options={
                'db_table': 'Receivables',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(db_column='shipmentid', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('date_shipped', models.DateTimeField(blank=True, db_column='shippedon', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Ready to Ship'), (2, 'Shipped')], default=0)),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('tracking', models.CharField(blank=True, max_length=50)),
                ('ship_by', models.IntegerField(blank=True, db_column='shipby', null=True)),
                ('purchase_order', models.CharField(blank=True, db_column='PO', max_length=50)),
                ('shipment_order', models.CharField(blank=True, db_column='SO', max_length=50)),
                ('third_party', models.CharField(blank=True, db_column='3rdparty', max_length=50)),
                ('third_party_address', models.TextField(blank=True, db_column='3rdpartyaddress')),
                ('third_party_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='3rdpartyphone', max_length=128)),
                ('third_party_per', models.CharField(blank=True, db_column='3rdpartyper', max_length=30)),
                ('third_party_received', models.CharField(blank=True, db_column='3rdpartyrecvd', max_length=16)),
                ('third_party_charges_advanced', models.CharField(blank=True, db_column='3rdpartychgadvanced', max_length=16)),
                ('pro_number', models.CharField(blank=True, db_column='pro', max_length=50)),
                ('purchase_order_number', models.CharField(blank=True, db_column='loadnum', max_length=50)),
                ('shipper_instructions', models.TextField(blank=True, db_column='shipperinstructions')),
                ('consignee_instructions', models.TextField(blank=True, db_column='consigneeinstructions')),
                ('inside_delivery', models.BooleanField(db_column='insidedelivery', default=False)),
                ('liftgate_required', models.BooleanField(db_column='liftgate', default=False)),
                ('appointment_required', models.BooleanField(db_column='appointment', default=False)),
                ('sort_segregation', models.BooleanField(db_column='sortseg', default=False)),
                ('shipment_class', models.CharField(blank=True, db_column='class', max_length=50)),
                ('pallet_count', models.IntegerField(blank=True, db_column='numpallets', null=True)),
                ('accounting_status', models.IntegerField(choices=[(0, 'INVQ'), (1, 'Pending'), (2, 'Submitted')], db_column='acctstatus')),
                ('invoice_number', models.IntegerField(blank=True, db_column='invoice', null=True)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('location', models.ForeignKey(blank=True, db_column='locationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Location')),
            ],
            options={
                'db_table': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDoc',
            fields=[
                ('id', models.AutoField(db_column='docid', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('basename', models.CharField(blank=True, max_length=255)),
                ('ext', models.CharField(blank=True, max_length=10)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, db_column='mimetype', max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='stamp')),
                ('shipment', models.ForeignKey(db_column='shipmentid', on_delete=django.db.models.deletion.CASCADE, to='ims.Shipment')),
            ],
            options={
                'db_table': 'ShipmentDocs',
            },
        ),
        migrations.CreateModel(
            name='ShipperAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(db_column='transactionid', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='stamp')),
                ('quantity', models.IntegerField(blank=True, db_column='qty', null=True)),
                ('quantity_remaining', models.BigIntegerField(blank=True, db_column='qtyremain', null=True)),
                ('is_outbound', models.BooleanField(db_column='direction', default=False)),
                ('cases', models.IntegerField(blank=True, null=True)),
                ('shipment_order', models.CharField(blank=True, db_column='SO', max_length=50)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('product', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='ims.Product')),
                ('receivable', models.ForeignKey(blank=True, db_column='receivableid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Receivable')),
                ('shipment', models.ForeignKey(blank=True, db_column='shipmentid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Shipment')),
                ('transfer_client', models.ForeignKey(blank=True, db_column='transfercustomerid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ims.Client')),
                ('transfer_product', models.ForeignKey(blank=True, db_column='transferproductid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ims.Product')),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='WarehouseUser',
            fields=[
                ('id', models.AutoField(db_column='wuserid', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='user', max_length=100)),
                ('password', models.CharField(blank=True, db_column='pass', max_length=255)),
                ('full_name', models.CharField(blank=True, db_column='fullname', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=192)),
                ('about', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('last_login', models.DateTimeField(db_column='lastlogin', null=True)),
                ('login_count', models.IntegerField(db_column='logintimes', default=0)),
                ('is_active', models.BooleanField(db_column='enable', default=True)),
                ('role', models.CharField(choices=[('accounting', 'Accounting'), ('warehouse', 'Warehouse')], max_length=30)),
                ('created_by', models.ForeignKey(blank=True, db_column='createdbyadminid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.AdminUser')),
            ],
            options={
                'db_table': 'wuser',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_address',
            field=models.ForeignKey(blank=True, db_column='shipperaddress', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.ShipperAddress'),
        ),
        migrations.AddField(
            model_name='palletcontents',
            name='product',
            field=models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='ims.Product'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='shipment',
            field=models.ForeignKey(db_column='shipmentid', on_delete=django.db.models.deletion.CASCADE, to='ims.Shipment'),
        ),
    ]
