# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('is_preferred', models.BooleanField(db_column='preferred', default=False)),
                ('is_enabled', models.BooleanField(db_column='enabled', default=True)),
                ('notes', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, db_column='coname', max_length=150, null=True)),
                ('has_warehousing', models.BooleanField(db_column='warehousing', default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Customer')),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
    ]
