# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Management', 'mgmt'), ('Client', 'client'), ('Warehouse', 'warehouse'), ('Accounting', 'accounting')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
