# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('mgmt', 'Management'), ('client', 'Client'), ('warehouse', 'Warehouse'), ('accounting', 'Accounting')], max_length=20),
        ),
    ]
