# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_auto_20170509_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custcontact',
            options={'ordering': ['-is_primary', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
