# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_clientuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='clientuser',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Client'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='last_login_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
