# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_auto_20170507_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustContact',
            fields=[
                ('id', models.AutoField(db_column='custcontactid', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, db_column='pass', max_length=255)),
                ('first_name', models.CharField(blank=True, db_column='fname', max_length=150)),
                ('last_name', models.CharField(blank=True, db_column='lname', max_length=150)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='tel', max_length=30)),
                ('phone_extension', models.CharField(blank=True, db_column='telext', max_length=5)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='mobile', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_column='enabled', default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='lastlogin', null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
            ],
            options={
                'db_table': 'CustContacts',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
