# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_auto_20170507_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
