# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_auto_20170507_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Client'),
        ),
    ]
