# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 14:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20170516_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='mobile_number',
            field=models.CharField(blank=True, db_column='cell', max_length=30),
        ),
        migrations.AlterField(
            model_name='custcontact',
            name='fax_number',
            field=models.CharField(blank=True, db_column='fax', max_length=30),
        ),
        migrations.AlterField(
            model_name='custcontact',
            name='mobile_number',
            field=models.CharField(blank=True, db_column='mobile', max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='fax_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, db_column='tel', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='third_party_phone_number',
            field=models.CharField(blank=True, db_column='3rdpartyphone', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
