# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_auto_20170507_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(db_column='locationid', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='tel', max_length=30)),
                ('phone_extension', models.CharField(blank=True, db_column='telext', max_length=5)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, db_column='addr', max_length=150)),
                ('address_2', models.CharField(blank=True, db_column='addr2', max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('non_us_state', models.CharField(blank=True, db_column='ostate', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('receiving_hours', models.CharField(blank=True, db_column='recvhours', max_length=100)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('customer_contact', models.ForeignKey(db_column='custcontactid', on_delete=django.db.models.deletion.CASCADE, to='ims.CustContact')),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
    ]
