# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_auto_20170507_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseUser',
            fields=[
                ('id', models.AutoField(db_column='wuserid', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='user', max_length=100)),
                ('password', models.CharField(blank=True, db_column='pass', max_length=255)),
                ('full_name', models.CharField(blank=True, db_column='fullname', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=192)),
                ('about', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('last_login', models.DateTimeField(db_column='lastlogin', null=True)),
                ('login_count', models.IntegerField(db_column='logintimes', default=0)),
                ('is_active', models.BooleanField(db_column='enable', default=True)),
                ('role', models.CharField(choices=[('accounting', 'Accounting'), ('warehouse', 'Warehouse')], max_length=30)),
                ('created_by', models.ForeignKey(blank=True, db_column='createdbyadminid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.AdminUser')),
            ],
            options={
                'db_table': 'wuser',
            },
        ),
    ]
