# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 08:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_auto_20170516_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['item_number']},
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
