# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_warehouseuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='productid', primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='PRID', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('packing', models.IntegerField(blank=True, null=True)),
                ('cases_inventory', models.IntegerField(blank=True, db_column='remain', null=True)),
                ('units_inventory', models.IntegerField(blank=True, db_column='totalq', null=True)),
                ('gross_weight', models.IntegerField(blank=True, db_column='GW', null=True)),
                ('is_domestic', models.BooleanField(db_column='prodtype', default=False)),
                ('client_product_id', models.CharField(blank=True, db_column='ctag', max_length=24)),
                ('contracted_quantity', models.BigIntegerField(blank=True, db_column='contqty', null=True)),
                ('is_active', models.BooleanField(db_column='active', default=True)),
                ('length', models.CharField(blank=True, max_length=10)),
                ('width', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('item_number', models.CharField(blank=True, db_column='itemnum', max_length=12)),
                ('account_prepay_type', models.IntegerField(choices=[(1, 'INVQ'), (2, 'Prepaid')], db_column='account')),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('location', models.ForeignKey(blank=True, db_column='locationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Location')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
