# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_auto_20170525_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='account_prepay_type',
            field=models.IntegerField(blank=True, choices=[(1, 'INVQ'), (2, 'Prepaid')], db_column='account', null=True),
        ),
    ]
