# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(db_column='shipmentid', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('date_shipped', models.DateTimeField(blank=True, db_column='shippedon', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Ready to Ship'), (2, 'Shipped')], default=0)),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('tracking', models.CharField(blank=True, max_length=50)),
                ('ship_by', models.IntegerField(blank=True, db_column='shipby', null=True)),
                ('purchase_order', models.CharField(blank=True, db_column='PO', max_length=50)),
                ('shipment_order', models.CharField(blank=True, db_column='SO', max_length=50)),
                ('third_party', models.CharField(blank=True, db_column='3rdparty', max_length=50)),
                ('third_party_address', models.TextField(blank=True, db_column='3rdpartyaddress')),
                ('third_party_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='3rdpartyphone', max_length=128)),
                ('third_party_per', models.CharField(blank=True, db_column='3rdpartyper', max_length=30)),
                ('third_party_received', models.CharField(blank=True, db_column='3rdpartyrecvd', max_length=16)),
                ('third_party_charges_advanced', models.CharField(blank=True, db_column='3rdpartychgadvanced', max_length=16)),
                ('pro_number', models.CharField(blank=True, db_column='pro', max_length=50)),
                ('purchase_order_number', models.CharField(blank=True, db_column='loadnum', max_length=50)),
                ('shipper_instructions', models.TextField(blank=True, db_column='shipperinstructions')),
                ('consignee_instructions', models.TextField(blank=True, db_column='consigneeinstructions')),
                ('inside_delivery', models.BooleanField(db_column='insidedelivery', default=False)),
                ('liftgate_required', models.BooleanField(db_column='liftgate', default=False)),
                ('appointment_required', models.BooleanField(db_column='appointment', default=False)),
                ('sort_segregation', models.BooleanField(db_column='sortseg', default=False)),
                ('shipment_class', models.CharField(blank=True, db_column='class', max_length=50)),
                ('pallet_count', models.IntegerField(blank=True, db_column='numpallets', null=True)),
                ('accounting_status', models.IntegerField(choices=[(0, 'INVQ'), (1, 'Pending'), (2, 'Submitted')], db_column='acctstatus')),
                ('invoice_number', models.IntegerField(blank=True, db_column='invoice', null=True)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('location', models.ForeignKey(blank=True, db_column='locationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Location')),
            ],
            options={
                'db_table': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='ShipperAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_address',
            field=models.ForeignKey(blank=True, db_column='shipperaddress', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.ShipperAddress'),
        ),
    ]
