# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_auto_20170508_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(db_column='receivableid', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('purchase_order', models.CharField(blank=True, db_column='PO', max_length=50)),
                ('shipment_order', models.CharField(blank=True, db_column='SO', max_length=50)),
                ('cases', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('product', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='ims.Product')),
            ],
            options={
                'db_table': 'Receivables',
            },
        ),
    ]
