# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 15:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_auto_20170525_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
