# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0010_receivable_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
