# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_client',
            field=models.ForeignKey(blank=True, db_column='transfercustomerid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_product',
            field=models.ForeignKey(blank=True, db_column='transferproductid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ims.Product'),
        ),
    ]
