# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0012_auto_20170526_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='product_id',
            new_name='pallet_id',
        ),
    ]
