# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0012_auto_20170508_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(db_column='palletid', primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_column='PID', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('client', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('shipment', models.ForeignKey(db_column='shipmentid', on_delete=django.db.models.deletion.CASCADE, to='ims.Shipment')),
            ],
            options={
                'db_table': 'Pallets',
            },
        ),
        migrations.CreateModel(
            name='PalletProducts',
            fields=[
                ('id', models.AutoField(db_column='onpalletid', primary_key=True, serialize=False)),
                ('cases', models.IntegerField(db_column='qty')),
                ('pallet', models.ForeignKey(db_column='palletid', on_delete=django.db.models.deletion.CASCADE, to='ims.Pallet')),
                ('product', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='ims.Product')),
            ],
            options={
                'db_table': 'OnPallet',
            },
        ),
    ]
