# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0013_pallet_palletproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PalletProducts',
            new_name='PalletContents',
        ),
        migrations.AlterModelOptions(
            name='palletcontents',
            options={'verbose_name_plural': 'pallet contents'},
        ),
    ]
