# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 15:17


from django.db import migrations, models
import ims.models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0015_auto_20170601_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdoc',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ims.models.get_image_path),
        ),
    ]
