# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:45


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0017_auto_20170602_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ancestors',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
