# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 22:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0021_auto_20170610_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['product__item_number']},
        ),
        migrations.AlterField(
            model_name='pallet',
            name='client',
            field=models.ForeignKey(blank=True, db_column='customerid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='shipment',
            field=models.ForeignKey(blank=True, db_column='shipmentid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Shipment'),
        ),
    ]
