# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0022_auto_20170611_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='pallet_id',
            field=models.CharField(db_column='PID', db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(db_column='PRID', db_index=True, max_length=10),
        ),
    ]
