# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-02 11:17


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0023_auto_20171002_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='customer_contact',
            field=models.ForeignKey(blank=True, db_column='custcontactid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.CustContact'),
        ),
    ]
