# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0024_auto_20181002_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='product',
            field=models.ForeignKey(db_column='productid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Product'),
        ),
    ]
