# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-02 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0025_auto_20181002_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdoc',
            name='shipment',
            field=models.ForeignKey(db_column='shipmentid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Shipment'),
        ),
    ]
