# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-07 12:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0026_auto_20181002_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.AutoField(db_column='bulkorderid', primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, default='', max_length=50)),
                ('date_ordered', models.DateTimeField(blank=True, db_column='stamp', null=True)),
                ('date_imported', models.DateTimeField(auto_now_add=True, db_column='imported')),
                ('purchase_order', models.CharField(blank=True, db_column='PO', default='', max_length=40)),
                ('date_delivery', models.DateTimeField(blank=True, db_column='deliverydate', null=True)),
                ('account_number', models.CharField(blank=True, db_column='accountnum', default='', max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=50)),
                ('location_address_1', models.CharField(blank=True, db_column='locaddress1', default='', max_length=200)),
                ('location_address_2', models.CharField(blank=True, db_column='locaddress2', default='', max_length=200)),
                ('location_city', models.CharField(blank=True, db_column='loccity', default='', max_length=160)),
                ('location_state', models.CharField(blank=True, db_column='locstate', default='', max_length=12)),
                ('location_zip', models.CharField(blank=True, db_column='loczip', default='', max_length=40)),
                ('client', models.ForeignKey(db_column='customerid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('location', models.ForeignKey(db_column='locationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Location')),
            ],
            options={
                'db_table': 'BulkOrders',
            },
        ),
        migrations.CreateModel(
            name='BulkOrderItem',
            fields=[
                ('id', models.AutoField(db_column='bulkorderitemid', primary_key=True, serialize=False)),
                ('item_number', models.CharField(blank=True, db_column='itemnum', default='', max_length=40)),
                ('quantity', models.DecimalField(blank=True, db_column='quantity', decimal_places=2, max_digits=10, null=True)),
                ('package_type', models.CharField(blank=True, db_column='pkgtype', default='', max_length=20)),
                ('split_flag', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], db_column='splitflag', default='', max_length=1)),
                ('product_name', models.TextField(blank=True, db_column='pname', default='')),
                ('bid_price', models.DecimalField(blank=True, db_column='bidprice', decimal_places=4, max_digits=12, null=True)),
                ('bulk_order', models.ForeignKey(db_column='bulkorderid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.BulkOrder')),
            ],
            options={
                'db_table': 'BulkOrderItems',
            },
        ),
    ]
