# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0027_bulkorder_bulkorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='shipment',
            field=models.ForeignKey(blank=True, db_column='shipmentid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Shipment'),
        ),
    ]
