# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-07 14:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0029_auto_20181007_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorderitem',
            name='product_name',
            field=models.TextField(blank=True, db_column='pname', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='consignee_instructions',
            field=models.TextField(blank=True, db_column='consigneeinstructions', default='', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_instructions',
            field=models.TextField(blank=True, db_column='shipperinstructions', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='third_party_address',
            field=models.TextField(blank=True, db_column='3rdpartyaddress', null=True),
        ),
    ]
