# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-07 14:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0030_auto_20181007_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='appointment_required',
            field=models.NullBooleanField(db_column='appointment', default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='inside_delivery',
            field=models.NullBooleanField(db_column='insidedelivery', default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='liftgate_required',
            field=models.NullBooleanField(db_column='liftgate', default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sort_segregation',
            field=models.NullBooleanField(db_column='sortseg', default=False),
        ),
    ]
