# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-08 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0031_auto_20181007_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_charge',
            field=models.DecimalField(blank=True, db_column='deliverycharge', decimal_places=2, max_digits=9, null=True),
        ),
    ]
