# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-09 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0034_actionlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_column='stamp'),
        ),
    ]
