# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-09 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0035_auto_20181009_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='units_inventory',
            new_name='units_inventory_old',
        ),
    ]
