# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0037_auto_20181009_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(db_column='returnid', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='stamp')),
                ('cases_damaged', models.IntegerField(blank=True, default=0, null=True)),
                ('cases_undamaged', models.IntegerField(blank=True, default=0, null=True)),
                ('date_reconciled', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, db_column='customerid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Client')),
                ('location', models.ForeignKey(blank=True, db_column='locationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Location')),
                ('product', models.ForeignKey(blank=True, db_column='productid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Product')),
            ],
            options={
                'db_table': 'Returns',
            },
        ),
    ]
