# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-10 20:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0038_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='date_reconciled',
            field=models.DateTimeField(blank=True, db_column='reconciled', null=True),
        ),
    ]
