# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-11 22:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0039_auto_20181010_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='date_created',
            field=models.DateTimeField(blank=True, db_column='stamp', null=True),
        ),
    ]
