# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0040_auto_20181011_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='ReturnedProduct',
        ),
        migrations.AddField(
            model_name='receivable',
            name='returned_product',
            field=models.ForeignKey(blank=True, db_column='returnid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.ReturnedProduct'),
        ),
    ]
