# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-12 23:15


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0041_auto_20181012_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedproduct',
            name='date_created',
        ),
        migrations.AddField(
            model_name='returnedproduct',
            name='date_returned',
            field=models.DateTimeField(db_column='stamp', null=True),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='client',
            field=models.ForeignKey(db_column='customerid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='location',
            field=models.ForeignKey(db_column='locationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Location'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='product',
            field=models.ForeignKey(db_column='productid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Product'),
        ),
    ]
