# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-19 20:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0045_transaction_is_scanned_to_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='appointment_required',
            field=models.BooleanField(db_column='appointment', default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='inside_delivery',
            field=models.BooleanField(db_column='insidedelivery', default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='liftgate_required',
            field=models.BooleanField(db_column='liftgate', default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sort_segregation',
            field=models.BooleanField(db_column='sortseg', default=False),
        ),
    ]
