# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-27 11:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0046_auto_20181019_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('percent_complete', models.FloatField(default=0)),
            ],
        ),
    ]
