# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-27 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0047_exporttask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportTask',
            new_name='AsyncTask',
        ),
    ]
