# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-27 12:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0048_auto_20181027_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='has_failed',
            field=models.BooleanField(default=False),
        ),
    ]
