# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-28 19:26


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0049_asynctask_has_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asynctask',
            name='result_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
