# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-01 19:28


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0053_remove_asynctask_result_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
    ]
