# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-04 23:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0054_auto_20181101_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fax_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
