# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-15 22:32


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0055_auto_20181104_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('company_name',)},
        ),
        migrations.AddField(
            model_name='location',
            name='contact_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.ClientUser'),
        ),
    ]
