# Generated by Django 2.1.8 on 2019-08-11 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0057_auto_20190408_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='view_order_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, db_column='adminid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.AdminUser'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='client',
            field=models.ForeignKey(blank=True, db_column='customerid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='product',
            field=models.ForeignKey(blank=True, db_column='productid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Product'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='warehouse_user',
            field=models.ForeignKey(blank=True, db_column='wuserid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.WarehouseUser'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdbyadminid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.AdminUser'),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='client',
            field=models.ForeignKey(db_column='customerid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='location',
            field=models.ForeignKey(db_column='locationid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Location'),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='shipment',
            field=models.ForeignKey(blank=True, db_column='shipmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Shipment'),
        ),
        migrations.AlterField(
            model_name='bulkorderitem',
            name='bulk_order',
            field=models.ForeignKey(db_column='bulkorderid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.BulkOrder'),
        ),
        migrations.AlterField(
            model_name='client',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.ClientUser'),
        ),
        migrations.AlterField(
            model_name='location',
            name='customer_contact',
            field=models.ForeignKey(blank=True, db_column='custcontactid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.CustContact'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='client',
            field=models.ForeignKey(blank=True, db_column='customerid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='shipment',
            field=models.ForeignKey(blank=True, db_column='shipmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Shipment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, db_column='locationid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Location'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='product',
            field=models.ForeignKey(db_column='productid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Product'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='returned_product',
            field=models.ForeignKey(blank=True, db_column='returnid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.ReturnedProduct'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='client',
            field=models.ForeignKey(db_column='customerid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='location',
            field=models.ForeignKey(db_column='locationid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Location'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='product',
            field=models.ForeignKey(db_column='productid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Product'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='location',
            field=models.ForeignKey(blank=True, db_column='locationid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_address',
            field=models.ForeignKey(blank=True, db_column='shipperaddress', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.ShipperAddress'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipmentdoc',
            name='shipment',
            field=models.ForeignKey(db_column='shipmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Shipment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receivable',
            field=models.ForeignKey(blank=True, db_column='receivableid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Receivable'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shipment',
            field=models.ForeignKey(blank=True, db_column='shipmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Shipment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_client',
            field=models.ForeignKey(blank=True, db_column='transfercustomerid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='ims.Client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_product',
            field=models.ForeignKey(blank=True, db_column='transferproductid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='ims.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouseuser',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdbyadminid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.AdminUser'),
        ),
    ]
