# Generated by Django 2.1.8 on 2019-11-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0059_auto_20191117_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, db_column='unitprice', decimal_places=5, max_digits=9, null=True),
        ),
    ]
