# Generated by Django 2.1.8 on 2019-11-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0060_auto_20191122_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, db_column='unitprice', decimal_places=5, max_digits=10, null=True),
        ),
    ]
