# Generated by Django 2.2.9 on 2020-02-01 15:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0062_auto_20200201_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='zip',
            new_name='postal_code',
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
