# Generated by Django 2.2.9 on 2020-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0063_auto_20200201_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(blank=True, db_column='GW', decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, db_column='unitprice', decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
