# Generated by Django 3.0.3 on 2020-02-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0065_auto_20200223_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='account_prepay_type',
            new_name='accounting_prepay_type',
        ),
    ]
