# Generated by Django 3.0.3 on 2020-03-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0066_auto_20200229_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receivable',
            field=models.ForeignKey(blank=True, db_column='receivableid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Receivable'),
        ),
    ]
