# Generated by Django 3.0.3 on 2020-03-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0067_auto_20200304_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipper_address',
            field=models.ForeignKey(blank=True, db_column='shipperaddress', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.ShipperAddress'),
        ),
    ]
