# Generated by Django 3.0.3 on 2020-03-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0068_auto_20200309_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipper_address',
            field=models.ForeignKey(blank=True, db_column='shipperaddress', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.ShipperAddress'),
        ),
    ]
