# Generated by Django 3.0.3 on 2020-03-14 15:58

from django.db import migrations
import ims.models


def save_all_users(apps, _):
    """
    Saves all User objects to ensure email addresses are stored as lowercase.
    """
    user_model = apps.get_model("ims", "User")

    for user in user_model.objects.all():
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0070_user_date_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=ims.models.LowercaseEmailField(max_length=191, unique=True, verbose_name='email address'),
        ),
        migrations.RunPython(
            save_all_users, reverse_code=migrations.RunPython.noop
        ),
    ]
