# Generated by Django 3.0.3 on 2020-03-15 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0071_auto_20200314_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_password_prompt_dismissed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
