# Generated by Django 3.0.3 on 2020-03-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0072_user_date_password_prompt_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shipment',
            field=models.ForeignKey(blank=True, db_column='shipmentid', null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Shipment'),
        ),
    ]
