# Generated by Django 3.0.3 on 2020-03-19 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0073_auto_20200318_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asynctask',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='asynctask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
