# Generated by Django 3.0.3 on 2020-03-28 08:19

from django.db import migrations, models
import uuid


def save_objects(apps, _):

    async_task_model: AsyncTask = apps.get_model("ims", "AsyncTask")

    for async_task in async_task_model.objects.all():
        async_task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0074_auto_20200319_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RunPython(save_objects, reverse_code=migrations.RunPython.noop),
    ]
