# Generated by Django 3.0.3 on 2020-03-28 22:56

from django.db import migrations, models
import uuid


def convert_ids(apps, _):

    shipment_doc_model: ShipmentDoc = apps.get_model("ims", "ShipmentDoc")

    for shipment_doc in shipment_doc_model.objects.all():
        shipment_doc.uuid = shipment_doc.uuid.replace('-', '')
        shipment_doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0075_auto_20200328_0819'),
    ]

    operations = [
        migrations.RunPython(convert_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shipmentdoc',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
