# Generated by Django 3.0.3 on 2020-03-28 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0076_auto_20200328_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentdoc',
            name='id',
        ),
        migrations.AlterField(
            model_name='shipmentdoc',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
