# Generated by Django 3.0.3 on 2020-03-29 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0078_auto_20200328_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdoc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
