# Generated by Django 3.0.3 on 2020-04-02 11:52

from django.db import migrations, models
import ims.models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0079_auto_20200329_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='pallet_id',
            field=models.CharField(db_column='PID', db_index=True, default=ims.models.generate_code, max_length=10, unique=True),
        ),
    ]
