# Generated by Django 3.0.3 on 2020-04-02 11:57

from django.db import migrations, models
import ims.models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0080_auto_20200402_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(db_column='PRID', db_index=True, default=ims.models.generate_code, max_length=10, unique=True),
        ),
    ]
