# Generated by Django 3.0.3 on 2020-04-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0081_auto_20200402_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(blank=True, db_column='GW', decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, db_column='unitprice', decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, max_length=10),
        ),
    ]
