# Generated by Django 3.0.7 on 2021-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0083_auto_20201220_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='netsuite_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
