# Generated by Django 3.0.7 on 2021-09-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0084_location_netsuite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='netsuite_submit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='netsuite_id',
            field=models.CharField(max_length=50),
        ),
    ]
