# Generated by Django 3.0.14 on 2022-12-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0086_auto_20211020_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accounting_prepay_type',
            field=models.IntegerField(blank=True, choices=[(1, 'INVQ'), (2, 'Prepaid'), (3, '3PL')], db_column='account', null=True),
        ),
    ]
