# Generated by Django 3.2.25 on 2024-09-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0087_auto_20221204_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distribution_center',
            field=models.CharField(blank=True, choices=[('castle', 'Castle'), ('county', 'County')], max_length=50),
        ),
    ]
