# Generated by Django 3.2.25 on 2024-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0088_product_distribution_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='netsuite_id',
            new_name='netsuite_client_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='netsuite_client_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='netsuite_address_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
